#!/usr/bin/env bash
# Bash script that install nginx and set a listening port to 80

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
