#!/usr/bin/env bash
# Bash script that will fix the nginx port issue
rm /etc/nginx/sites-enabled/default
sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sed -i "s/ipv6only=on//" /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
