#!/usr/bin/env bash
# This script manages manage_my_process

stop_process(){
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
}

start_process(){
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
}

if [[ "$1" == "start" ]]
then
	start_process
	echo "manage_my_process started"
elif [[ "$1" == "stop" ]]
then
	stop_process
	echo "manage_my_process stopped"
elif [[ "$1" == "restart" ]]
then
	stop_process
	start_process
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
