#!/usr/bin/env bash
# This script prints "Best School" 10 times and prints "Hi" after the 9th iteration
i="0"
while [ $i -lt 10 ]
do
  echo "Best School"
  if [ $i -eq 8 ]
  then
	echo "Hi"
  fi
i=$((i+1))
done
