#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and prints "bad luck from China" at the 4th, "bad luck from Japan" at the 9th and "bad luck from Italy" at the 17th
i="1"
while [ $i -le 20 ]
do
  echo $i
  case $i in
  "4")
	echo "bad luck from China"
  ;;

  "9")
	echo "bad luck from Japan"
  ;;

  "17")
	echo "bad luck from Italy"
  ;;
  esac
i=$((i+1))
done
